# Generated by Django 5.2.5 on 2026-02-05 09:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='著者名')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='ページ数')),
                ('status', models.CharField(choices=[('unread', '未読'), ('reading', '読書中'), ('finished', '読了')], default='unread', max_length=20, verbose_name='ステータス')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='読了日')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='おすすめ度')),
                ('one_line_summary', models.CharField(blank=True, max_length=300, verbose_name='一言要約')),
                ('impression_during', models.TextField(blank=True, verbose_name='読書中の感想')),
                ('impression_after', models.TextField(blank=True, verbose_name='読了後の感想')),
                ('comparison_notes', models.TextField(blank=True, verbose_name='他作品と比べた感想')),
                ('theme_notes', models.TextField(blank=True, verbose_name='作品のテーマについての感想')),
                ('unwritten_notes', models.TextField(blank=True, verbose_name='書かれていないものについての感想')),
                ('era_common_notes', models.TextField(blank=True, verbose_name='時代の共通点としての感想')),
                ('universal_theme_notes', models.TextField(blank=True, verbose_name='普遍的なテーマとしての感想')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Note',
                'verbose_name_plural': 'Reading Notes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
