# Generated by Django 5.2.5 on 2026-02-05 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingnote',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='reading_notes/covers/', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='readingnote',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='ラベル')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='reading_notes.readingnote')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
