# Generated by Django 5.2.5 on 2026-02-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_notes', '0002_readingnote_cover_image_readingnote_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingnote',
            name='category',
            field=models.CharField(blank=True, choices=[('novel', '小説'), ('technical', '専門書'), ('reading', '読み物'), ('magazine', '雑誌')], max_length=20, verbose_name='種類'),
        ),
    ]
