# Generated by Django 5.2.5 on 2026-02-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_notes', '0003_readingnote_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='kind',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('rakuten', '楽天')], default='amazon', max_length=20, verbose_name='種類'),
        ),
        migrations.AlterField(
            model_name='affiliatelink',
            name='label',
            field=models.CharField(blank=True, max_length=100, verbose_name='ラベル'),
        ),
    ]
