# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reading_notes", "0004_affiliatelink_kind_alter_affiliatelink_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingnote",
            name="reading_purpose",
            field=models.TextField(blank=True, verbose_name="この本を読む目的・テーマ"),
        ),
    ]

