# Generated by Django 5.2.5 on 2026-05-22 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_notes', '0005_readingnote_reading_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingnote',
            name='reading_purpose',
            field=models.TextField(blank=True, verbose_name='この本を読む目的'),
        ),
        migrations.CreateModel(
            name='ReadingThemeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タグ名')),
                ('knowledge_url', models.URLField(blank=True, max_length=500, verbose_name='Knowledge Base URL')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Theme Tag',
                'verbose_name_plural': 'Reading Theme Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='readingnote',
            name='theme_tags',
            field=models.ManyToManyField(blank=True, related_name='reading_notes', to='reading_notes.readingthemetag', verbose_name='テーマタグ'),
        ),
        migrations.AddConstraint(
            model_name='readingthemetag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_reading_theme_tag_per_owner'),
        ),
    ]
