# Generated by Django 5.2.5 on 2026-02-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickMemo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence_id", models.PositiveIntegerField(verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="タイトル")),
                ("body", models.TextField(verbose_name="本文")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "owner",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quick_memos", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-sequence_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="quickmemo",
            constraint=models.UniqueConstraint(fields=("owner", "sequence_id"), name="unique_sequence_id_per_owner"),
        ),
    ]

