# Generated by Django 5.2.5 on 2025-08-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='著者名'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ジャンル'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='isbn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='knowledge_type',
            field=models.CharField(choices=[('normal', '一般'), ('book', '書籍'), ('paper', '論文')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='page',
            field=models.IntegerField(blank=True, null=True, verbose_name='ページ数'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='1ページの大きさ'),
        ),
    ]
