# Generated by Django 5.2.5 on 2026-05-26 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_knowledge_author_knowledge_genre_knowledge_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='learning_logs/images/', verbose_name='画像')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='learning_logs.knowledge')),
            ],
        ),
    ]
