# Generated by Django 5.2.5 on 2025-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_tag_knowledge_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
