# Generated by Django 5.2.5 on 2025-08-15 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('action_type', models.CharField(choices=[('読書', '読書'), ('研究', '研究'), ('バイト', 'バイト'), ('娯楽', '娯楽'), ('ジム', 'ジム'), ('その他', 'その他')], max_length=10, verbose_name='種類')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期日')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='スケジュール済み')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('text1', models.CharField(blank=True, max_length=200, verbose_name='目標(Specific)')),
                ('text2', models.CharField(blank=True, max_length=200, verbose_name='測定可能(Measurable)')),
                ('text3', models.CharField(blank=True, max_length=200, verbose_name='達成可能(Achievable)')),
                ('completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='開始時刻')),
                ('end_time', models.DateTimeField(verbose_name='終了時刻')),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='todo.actionitem', verbose_name='アクション')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タスク名')),
                ('completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('position', models.IntegerField(default=0, verbose_name='表示順')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.schedule')),
            ],
        ),
    ]
