# Generated by Django 5.1 on 2024-08-27 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('deadline', models.DateField(verbose_name='締切')),
                ('text1', models.CharField(default='none', max_length=200)),
                ('text2', models.CharField(default='none', max_length=200)),
                ('text3', models.CharField(default='none', max_length=200)),
                ('text4', models.CharField(default='none', max_length=200)),
                ('int1', models.IntegerField(default=0)),
                ('int2', models.IntegerField(default=0)),
                ('int3', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date1', models.DateTimeField(default=django.utils.timezone.now)),
                ('date2', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
