# Generated by Django 5.1 on 2024-09-20 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='本の名前')),
                ('page', models.IntegerField(default=0, verbose_name='ページ数')),
                ('size', models.IntegerField(default=0, verbose_name='1ページの大きさ')),
                ('text1', models.CharField(max_length=500, verbose_name='章構成')),
                ('keyword', models.CharField(max_length=500, verbose_name='キーワード')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('genre', models.CharField(max_length=200, verbose_name='ジャンル')),
                ('text3', models.CharField(max_length=200)),
                ('text4', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('int2', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date1', models.DateTimeField(default=django.utils.timezone.now)),
                ('date2', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='論文の名前')),
                ('page', models.IntegerField(default=0, verbose_name='ページ数')),
                ('text1', models.CharField(max_length=500, verbose_name='章構成')),
                ('keyword', models.CharField(max_length=500, verbose_name='キーワード')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('genre', models.CharField(max_length=200, verbose_name='ジャンル')),
                ('text3', models.CharField(max_length=200)),
                ('text4', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('int2', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date1', models.DateTimeField(default=django.utils.timezone.now)),
                ('date2', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='task_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='タスクの種類'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='date1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='タスク終了時の時刻'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(verbose_name='締切(T)'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='int1',
            field=models.IntegerField(default=0, verbose_name='基本スコア'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='int2',
            field=models.IntegerField(default=0, verbose_name='タスクの状態'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='int3',
            field=models.IntegerField(default=0, verbose_name='タスクのスコア'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text1',
            field=models.CharField(max_length=200, verbose_name='S(何を達成したいのか。)'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text2',
            field=models.CharField(max_length=200, verbose_name='M(達成できたかどうかを測る定量的な指標)'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text3',
            field=models.CharField(max_length=200, verbose_name='A(達成するために必要なスキル)'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text4',
            field=models.CharField(max_length=200, verbose_name='R(関連タスク)'),
        ),
    ]
