# Generated by Django 5.2.5 on 2025-08-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='text1',
            field=models.CharField(blank=True, max_length=200, verbose_name='目標(Specific)'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='text2',
            field=models.CharField(blank=True, max_length=200, verbose_name='測定可能(Measurable)'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='text3',
            field=models.CharField(blank=True, max_length=200, verbose_name='達成可能(Achievable)'),
        ),
    ]
