# Generated by Django 5.2.5 on 2025-08-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_actionitem_description_actionitem_text1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
    ]
