# Generated by Django 5.2.5 on 2025-08-13 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
        ('todo', '0002_book_paper_todo_task_type_alter_todo_date1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_logs.knowledge'),
        ),
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='keyword',
            field=models.TextField(max_length=500, verbose_name='キーワード'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text1',
            field=models.TextField(max_length=500, verbose_name='章構成'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='text3',
            field=models.CharField(max_length=200, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='text4',
            field=models.CharField(max_length=200, verbose_name='著者名'),
        ),
    ]
