# Generated by Django 5.2.5 on 2025-12-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_schedule_action_item_actioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncategory',
            name='track_pages',
            field=models.BooleanField(default=False, verbose_name='ページ数を記録する'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='ページ数'),
        ),
    ]
