# Generated by Django 5.2.5 on 2025-08-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_knowledge_todo_owner_alter_book_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='owner',
        ),
    ]
