# Generated by Django 5.2.5 on 2025-12-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_actioncategory_track_pages_schedule_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='終了ページ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='開始ページ'),
        ),
    ]
