# Generated by Django 5.2.5 on 2025-08-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='完了フラグ'),
        ),
    ]
