# Generated by Django 5.2.5 on 2025-08-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_actionitem_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='action_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='todo.actionitem', verbose_name='アクション'),
        ),
    ]
