# Generated by Django 5.2.5 on 2025-12-09 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_schedule_end_page_schedule_start_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionitem',
            name='action_type',
        ),
    ]
