# Generated by Django 5.2.5 on 2025-08-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_knowledge_todo_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
