# Generated by Django 5.2.5 on 2026-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_actionitem_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title_override',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title override'),
        ),
    ]
