# Generated by Django 5.2.5 on 2025-08-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_delete_book_delete_paper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
        migrations.AddField(
            model_name='todo',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
    ]
