# Generated by Django 5.2.5 on 2026-05-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='book_author',
            field=models.CharField(blank=True, max_length=100, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/book_images/', verbose_name='書籍画像'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='reading_purpose',
            field=models.TextField(blank=True, verbose_name='読む目的'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='theme',
            field=models.CharField(blank=True, max_length=100, verbose_name='テーマ'),
        ),
    ]
