# Generated by Django 5.2.5 on 2025-08-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_todo_date2_remove_todo_image_todo_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
    ]
