# Generated by Django 5.2.5 on 2025-08-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_type',
            field=models.CharField(choices=[('読書', '読書'), ('研究', '研究'), ('バイト', 'バイト'), ('娯楽', '娯楽'), ('ジム', 'ジム'), ('その他', 'その他')], default='その他', max_length=10, verbose_name='タスクの種類'),
        ),
    ]
