# Generated by Django 5.2.5 on 2025-10-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='メンバー名')),
                ('research_group', models.CharField(choices=[('COMM', '通信'), ('GRAPH', 'グラフ')], max_length=10, verbose_name='所属グループ')),
                ('is_active', models.BooleanField(default=True, verbose_name='在籍中')),
            ],
            options={
                'verbose_name': '研究室メンバー',
                'verbose_name_plural': '研究室メンバー',
            },
        ),
    ]
