# Generated by Django 5.2.5 on 2025-10-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='academic_year',
            field=models.CharField(choices=[('B4', '学部4年'), ('M1', '修士1年'), ('M2', '修士2年'), ('D', '博士課程'), ('PD', '研究員'), ('STAFF', '教員')], default='M1', max_length=10, verbose_name='学年'),
        ),
    ]
